version: '3.4'

services:
  mvcmusicstore:
    image: ${DOCKER_REGISTRY-}mvcmusicstore
    build:
      context: .\MvcMusicStore
      dockerfile: Dockerfile
      #depends_on:#
        #- sql#
  #sql:#
    #image: microsoft/mssql-server-windows#
    #environment:#
    #- "ACCEPT_EULA='Y'"#
    #- "sa_password=Password123!"#